import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Astromania 🌔</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <video className="h-min" src={"/astromania.mp4"} autoPlay loop muted>Your browser does not support the video tag.</video>
        {/* nota: agregar muted porque sino no anda el autoplay */}
      </main>

    </div>
  )
}
